
module.exports = {
    ACT_JOIN_CHAT_ROOM: 1,
    ACT_JOIN_TABLE: 2,
    ACT_LEAVE_CHAT_ROOM: 3,
    ACT_LEAVE_TABLE: 4,
    ACT_SAY_CHAT_ROOM: 5,
    ACT_MOVE_CHAT_ROOM: 6,
    
    ACT_JOIN_FAMILY: 11,
    ACT_GET_HOUSES_DATA: 21,
    ACT_GET_FAMILY_DATA: 22,
    ACT_GET_PEOPLE_DATA: 23,
    ACT_GET_COUNTRYSIDE_DATA: 24,
    ACT_GET_TROPHY: 25,
    ACT_UPDATE_SKILL: 51,
    ACT_UPDATE_COUNTRYSIDE: 52,
    ACT_UPDATE_NICKNAME: 53,
    ACT_GET_ADMIN_DATASET: 91,
    ACT_ADMIN_CREATE_GAME: 92,
}